LIBNAME MHA501 '/home/u49592336/sasuser.v94';

PROC IMPORT DATAFILE='/home/u49592336/sasuser.v94/MHA501/diabetes.xlsx' DBMS=XLSX
	OUT=MHA501.DIABETES;
	GETNAMES=YES;
RUN;


PROC SORT DATA = MHA501.DIABETES;
	BY GENDER;
PROC MEANS DATA = MHA501.DIABETES;
	BY GENDER;
	VAR AGE STABGLU HEIGHT WEIGHT CHOL HDL RATIO;
RUN;


PROC CONTENTS DATA = MHA501.TITANIC;
RUN;

PROC FREQ DATA = MHA501.TITANIC;
	TABLES PCLASS SURVIVED FEMALE;
RUN;

PROC FREQ DATA = MHA501.TITANIC;
	TABLES PCLASS * SURVIVED/CHISQ;
RUN;